# Parking services 
# True if they still exist, else False (None if not looked up or unsure)
ps = { # Parking services of zirngibl:2022:PrevalenceOfParking
	"101domain": True,
	"123reg_parking": True,
	"123reg_placeholder": True,
	"22_cn": True,
	"above": True,
	"afternic": True,
	"alibaba_expired": True,  # alibabacloud.com
	"aliyun_expired": False,  # redirects to alibabacloud
	"alter_com": False,
	"aruba_it": True,
	"bluehost": True,
	"bodis": True,
	"brandbucket": True,
	"dancom": True,
	"dne_com": True,
	"dnspod": True,
	"domain_io": True,  # uses dan, escrow and godaddy
	"domainbox_expired": True,
	"domainbrokers": True, # very simple, only via contact: https://domainbrokers.se/
	"domaincntrol": None, # Unsure: https://lookyloo.circl.lu/tree/46ce19f3-7da4-4cd6-8394-120629a14eb3
	"domaincom": True,
	"domaindiscount24": True,
	"domainist": False, 
	"domainmarket": True,
	"domainmarkt_de": True, # very small
	"domainname_de": True,
	"domainname_shop": True,
	"domainorder": True,
	"domainparking_ru": True,
	"domainpower": False, # was purchased by trillion
	"domainprofi": True,
	"domainrecover": True,
	"domainsponsor_rookmedia": False,
	"dynadot": True,
	"efty": None,
	"enom": None,
	"epik": None,
	"expiereddnsmanager": None,
	"fabulous_directnic": True,
	"fasthosts": None,
	"flippa": True,
	"forpsi": None,
	"gabia": None,
	"godaddy_cashparking": True,
	"godaddy_parking": True,
	"hostgator": None,
	"hostinger": True,
	"hostnet": None,
	"hostpoint": None,
	"hugedomains": True,
	"internetvikings": True,
	"linkuwant": True,
	"markmonitor": None,
	"namebright": None,
	"namecheap": True,
	"namecheap_pending": True,
	"nameprovider": None,
	"onecom": None,
	"parkingcrew": True,
	"parklogic": True,
	"perfectdomain": None,
	"regru": None,
	"regtons": None,
	"savcom": True,
	"sedo": True,
	"sitematrix": None,
	"skenzo": True,
	"snparking": None,
	"sonexo_dnfs24": None,
	"squadhelp": None,
	"theparkingplace": True,
	"traffic_club": None,
	"transip": None,
	"trustednam_es": None,
	"tucows": None,
	"turkticaret": None,
	"uniregistry": True,
	"unknown_surveysmiles": None,
	"voodoo": False,
	"wangguai": None,
	"wedos": None,
	"west_cn": None
}
missing = { # parking services that are not included in the previous list
    "smartName": True,
    "zeropark": True,
    "Escrow.com": True, #since 1999
    "uk2.net": True,
    "dominioamigo.com.co": False, # delisted from google https://transparencyreport.google.com/copyright/domains/dominioamigo.com.co
    "atom": True,
    "denic": None,
    "nomino": None,
    "trillion.com": None
    
}